zon2nix: remove file url support
nix now fails with
```
  error: access to absolute path '/nix/store/xwaac58ji3kwkra5wmcfl6siszi82kpq-file-url-test.tar.gz' is forbidden in pure evaluation mode (use '--impure' to override)
```

Thus we won't support it either, zon2json-lock should still support the
file urls however.